# Generated by Django 3.0.8 on 2020-07-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='is_correct',
            new_name='is_live',
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='submission',
            name='text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
