# Generated by Django 3.0.8 on 2020-07-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20200706_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
